### PR TITLE
 add transfer coins

### PR DESCRIPTION
**Pull request by wenshenjun**
Now can transfer coins.

### CODE REVIEW

**Comment by perfectmak** [comment]
@wenshenjun Thanks for the contribution. 

I'll properly review tomorrow, but I did a quick glance and I have two suggestion.
- Please update the Readme.md with instructions on transferring the coins.
- Also, in addition to your test, please check to see if the recipient's balance gets updated.

Thank you. I'll go through the code properly and submit proper reviews if there are more.

**Comment by wenshenjun** [comment]
> @wenshenjun Thanks for the contribution.
> 
> I'll properly review tomorrow, but I did a quick glance and I have two suggestion.
> 
> * Please update the Readme.md with instructions on transferring the coins.
> * Also, in addition to your test, please check to see if the recipient's balance gets updated.
> 
> Thank you. I'll go through the code properly and submit proper reviews if there are more.

Thank you, I have updated the code as you requested.

When the  transferring the coins request is too frequent，Update balance is not very fast, so i add expect AcStatus equal AdmissionControlStatus.ACCEPTED

**Comment by wenshenjun** [comment]
by the way, my nodejs version is v12.1.0

**Comment by wenshenjun** [comment]
I also update KeyFactory code, from same mnemonic, to generate key is the same of the libra cli generate.

**Comment by wenshenjun** [comment]
You might need read this code https://github.com/libra/libra/blob/master/client/libra_wallet/src/key_factory.rs#L183, and r https://github.com/DaGenix/rust-crypto/blob/master/src/pbkdf2.rs. 
We can replace `pbkdf2()` with https://github.com/crypto-browserify/pbkdf2.

**Pull request merged**
